config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  devise_scope :user do
    authenticated :user do
       root 'profile#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  get ':username', to: 'users#show'
  get '/:username/followers', to: 'users#followers'
  get '/:username/following', to: 'users#following'
  resources :posts, only: [:create, :destroy]
  resources :relations, only: [:create, :destroy]
  resources :users do
    get :search, on: :collection
    resources :notifications, only: [:index]
    member do
      get :followers, :following
    end
  end

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  belongs_to :follower, class_name: "User"
  validates_presence_of :user, :follower
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :content, :user
  validates_length_of :content, :maximum => 255
end

app/models/relation.rb
class Relation < ActiveRecord::Base
	belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates_presence_of :follower_id, :followed_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessor :login

  validates :username, :presence => true, :uniqueness => { :case_sensitive => false }

  has_many :posts
  has_many :notifications
  has_many :active_relations, class_name:  "Relation",
                                   foreign_key: "follower_id",
                                   dependent:   :destroy
  has_many :passive_relations, class_name:  "Relation",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relations, source: :followed
  has_many :followers, through: :passive_relations

  mount_uploader :avatar, AvatarUploader

  scope :by_username, -> username { where("username ilike (?)","%#{username}%") }

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions.to_h).first
    end
  end

  def follow(user_follow)
    active_relations.create(followed_id: user_follow.id)
    Notification.create(user: user_follow, follower: self)
  end

  def unfollow(user_unfollow)
    active_relations.find_by_followed_id(user_unfollow.id).destroy
  end

  def following?(target_user)
    following.include?(target_user)
  end

  def picture
    avatar.url.present? ? avatar.try(:url): 'avatar.jpg'
  end

  def newsfeed
    ids = [id] + following.pluck(:id)
    Post.where('user_id in (?)', ids).order('created_at desc')
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password, :full_name, :about, :avatar) }
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
	before_action :authenticate_user!
	
	def index
		@user = User.find params[:user_id]
		@notifications = @user.notifications.order('created_at desc')
		@notifications.where(read_at: nil).update_all(read_at: DateTime.current)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!
	
	def create
		post = Post.new(post_params)
		if post.save
			flash[:notice] = 'Stringed it successfully!'
		else
			flash[:alert] = post.errors.full_messages
		end
			redirect_to authenticated_root_path
	end

	def destroy
		post = Post.find params[:id]
		if post.destroy
			flash[:alert] = 'String deleted!'
		end
			redirect_to authenticated_root_path		
	end

	private
    def post_params
      params.require(:post).permit(:content, :user_id)
    end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController

	before_action :authenticate_user!
	
	def index
		@user = current_user
		@nf = @user.newsfeed
	end
end

app/controllers/relations_controller.rb
class RelationsController < ApplicationController
	before_action :authenticate_user!
	def create
		followed = User.find params[:followed_id]
		current_user.follow(followed)
		redirect_to :back, notice: "You are now following @#{followed.username}"
	end

	def destroy
		followed = User.find params[:id]
		current_user.unfollow(followed)
		redirect_to :back, notice: "You are not following @#{followed.username} anymore"
		
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	has_scope :by_username

	def show
		@user = User.find_by_username(params[:username])
		redirect_to authenticated_root_path unless @user.present?
	end

	def followers
		@user = User.find_by_username(params[:username])
		if @user.present?
			@followers = @user.followers
		else
			redirect_to authenticated_root_path
		end
	end

	def following
		@user = User.find_by_username(params[:username])
		if @user.present?
			@following = @user.following
		else
			redirect_to authenticated_root_path
		end
	end

	def search
		@users = apply_scopes(User).all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/relations_helper.rb
module RelationsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stringer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= nav_bar fixed: :top, brand: "Stringer", brand_link: authenticated_root_path do %>
  <% if current_user.present? %>
    <%= badge(current_user.notifications.where(read_at: nil).count) %>
    <%= menu_group do %>
      <%= menu_item "Notifications", user_notifications_path(current_user) %>
    <% end %>
		<%= menu_group pull: :right do %>
        <%= menu_item "Edit Profile", edit_user_registration_path(current_user) %>
        <%= menu_item "Log Out", destroy_user_session_path, :method => :delete %>
    <% end %>
  <% end %>
  <div class="col-sm-3 col-md-3 pull-right">
            <!-- <form class="navbar-form" role="search">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search" name="q">
                    <div class="input-group-btn">
                        <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
                    </div>
                </div>
            </form> -->
            <%= form_tag search_users_path, class: 'navbar-form', role: 'search', method: :get do %>
              <div class='input-group'>
                <%= text_field_tag :by_username, nil, placeholder: '@Username', class: 'form-control' %>
                <div class="input-group-btn">
                  <%= button_tag(type: 'submit', class: "btn btn-default") do %>
                    <i class="fa fa-search"></i>
                  <% end %>
                </div>
              </div> 
            <% end %>
        </div>  
<% end %>
<%= bootstrap_flash %>
<div class="container-fluid">
	<%= yield %>
</div>
<nav class="navbar navbar-inverse navbar-fixed-bottom">
</nav>

</body>
</html>

app/views/notifications/_notification.html.erb
<div class='row margin post'>
	<div class='float_left'><%= image_tag(notification.follower.picture , class: 'avatar_sm' ) %>
			<%= render partial: "users/follow_button", locals: {user_follow: notification.follower} %>
	</div>
	<div class='float_left width_85'><h4><small><%= time_ago_in_words(notification.created_at) %> ago</small></h4><h4><%= link_to "@#{notification.follower.username}:", "/#{notification.follower.username}" %> is now following you.</div>
</div>

app/views/notifications/index.html.erb
<div class="row">
	<%= render partial: "profile/profile", locals: {user: @user} %>
	  <div class="col-md-8 cont">
	  	<h3>Notifications:</h2><hr>
	  	<% @notifications.each do |notification|%>
				<div>
					<%= render notification%>
					<hr>
				</div>
			<%end%>
	  </div>
</div>

app/views/posts/_new.html.erb
<%= simple_form_for(current_user.posts.new, html: { class: 'form-horizontal' }) do |f| %>
	<%= f.input :content, as: :text, label: false %>
	<%= f.input :user_id, as: :hidden %>
	<%= f.submit "String It!", class: 'btn btn-success' %>
<% end %>

app/views/posts/_post.html.erb
<div class='row margin post'>
	<div class='float_left'><%= image_tag(post.user.picture , class: 'avatar_sm' ) %>
	<% if current_user %>
		<% if current_user == post.user %>
			<div><%= link_to 'Delete String', post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %></div>
		<% end %>
	<% end %>
	</div>
	<div class='float_left width_85'><h4><%= link_to "@#{post.user.username}:", "/#{post.user.username}" %><h6><small><%= time_ago_in_words(post.created_at) %> ago</small></h6><small><%= post.content %></small></h4></div>
</div>

app/views/users/_follow_button.html.erb
<% if current_user.following?(user_follow) %>
	<div><%= link_to 'Unfollow', relation_path(user_follow), method: :delete, class: 'btn btn-danger'%></div>
<% else %>
	<div><%= link_to 'Follow', relations_path( followed_id: user_follow.id), method: :post , class: 'btn btn-primary'%></div>
<% end %>

app/views/users/_user.html.erb
<div class='row margin post'>
	<div class='float_left'><%= image_tag(user.picture , class: 'avatar_sm' ) %>
	<% if current_user %>
		<% if current_user != user %>
			<%= render partial: "follow_button", locals: {user_follow: user} %>
		<% end %>
	<% end %>
	</div>
	<div class='float_left width_85'><h4><%= link_to "@#{user.username}:", "/#{user.username}" %><br><small><%= user.about %></small></h4></div>
</div>

app/views/users/followers.html.erb
<div class="row">
	<%= render partial: "profile/profile", locals: {user: @user} %>
	  <div class="col-md-8 cont">
	  	<h3><%= @user.username %>´s followers:</h2><hr>
	  	<% @followers.each do |follower|%>
				<div>
					<%= render partial: "user", locals: {user: follower} %>
					<hr>
				</div>
			<%end%>
	  </div>
</div>

app/views/users/following.html.erb
<div class="row">
	<%= render partial: "profile/profile", locals: {user: @user} %>
	  <div class="col-md-8 cont">
	  	<h3><%= @user.username %> is following:</h2><hr>
	  	<% @following.each do |following|%>
				<div>
					<%= render partial: "user", locals: {user: following} %>
					<hr>
				</div>
			<%end%>
	  </div>
</div>

app/views/users/search.html.erb
<div class="row">
	  <div class="col-md-8 col-md-offset-3">
	  	<div class='cont' >
		  	<h3>Search results:</h3><hr>
		  	<% if @users.any? %>
			  	<% @users.each do |user|%>
						<div>
							<%= render partial: "user", locals: {user: user} %>
							<hr>
						</div>
					<%end%>
				<%end%>
			</div>
	  </div>
</div>

app/views/users/show.html.erb
<div class="row">
	<%= render partial: "profile/profile", locals: {user: @user} %>
	  <div class="col-md-8 cont">
	  	<h3><%= @user.username %>´s Strings:</h2><hr>
	  	<% @user.posts.order('created_at desc').each do |post|%>
				<div>
					<%= render partial: "posts/post", locals: {post: post} %>
					<hr>
				</div>
			<%end%>
	  </div>
</div>